role :libs, "10.0.1.22", "10.0.1.20"
role :info, "10.0.1.20"

desc "List all files"
task :list_files, :roles => :libs do
  run "ls -al"
end

desc "List the Username"
task :whois_user, :roles => :info do
  run "echo $USER"
end