#!/bin/bash

# This script takes in 3 parameters:
# (1) ftp server
# (2) ftp username
# (3) ftp password

# USAGE in the command line:
# ftp-build <server> <username> <password>

# variables
server=$1
username=$2
password=$3

# check number of input arguments
if [ $# -ne 3 ]; then
  echo "Hey! The 3 arguments for username and password are not provided!";
  exit -1;
fi

# take the latest file e.g. movie.mp4 from the Desktop
video=`ls -t ~/Desktop| head -n1`

#ftp into the server
ftp -n <<EOF
open $server
user $username $password
cd public_html/build/videos
put "~/Desktop/$video" $video
EOF