#!/bin/bash

# This script takes in 3 parameters:
# (1) episode number
# (2) episode topic in lowercase
# (3) episode topic in uppercase

# USAGE in the command line:
# start-build 099 javascript JavaScript

# variables
EPISODE="Topic: `basename $1` [episode]"
TOPIC="Topic: `basename $2` [topic]"
CAP="Cap: `basename $3` [cap]"

# check number of input arguments
if [ $# -ne 3 ]; then
  echo $EPISODE;
  echo $TOPIC;
  echo $CAP;
  exit -1;
fi

mkdir $1-$2;
cd $1-$2;
touch readme.md
echo "New episode directory and readme file created"

# readme.md starter
echo "#Build Podcast ep $1 - $3" >> readme.md
echo -e "For explanatory notes, video file, tool version and other info, please refer to the [screencast link](http://build-podcast.com/$2/)\n" >> readme.md
echo -e "[$3](#)\n" >> readme.md
echo -e "version: \n" >> readme.md

echo -e "#Background on $3 \n1.\n" >> readme.md
echo -e "#Things to learn with $3 \n\n##1. install\n1.\n" >> readme.md
echo -e "#More Resources on $3 \n1. \n" >> readme.md
echo -e "#Related Build Podcast episodes\n1. \n" >> readme.md
echo -e "#Build Link of this episode" >> readme.md
