#!/usr/bin/env node

// modules
var program = require('commander');
var sh = require("execSync");
var clc = require('cli-color');

// options and arguments
program
  .version('0.0.1')
  .option('-f, --folder <type>', 'Add demo folder name')
  .option('-n, --num <type>', 'Add episode number NNN')
  .option('-e, --episode_lowercase <type>', 'Add episode name in lowercase E.g. virtualbox')
  .parse(process.argv);

// project specific variables
var config = {

}

if (program.folder && program.num && program.episode_lowercase) {

  console.log('\nYou have started to publish new Build Podcast episode:');

  // ------------ Stop Apache server -----------//
  console.log('Stopping apache server');
  sh.run('sudo apachectl stop');

  // ------------ Video normalisation -----------//
  sh.run('norm ' + program.num + '-' + program.episode_lowercase + '.mp4');
  console.log('\nNormalised video');

  // ------------ Copy demo files -----------//

  // ------------ Video upload to FTP  ------------ //



  // ------------ Video upload to YouTube  ------------ //



  // ------------ Video upload to Vimeo  ------------ //

} else {
  console.log('Missing arguments :(');
  program.help();
}
